import Head from "next/head";
import styles from "@/styles/List.module.scss";
import Header from "@/components/Header";
import ListContainer from "@/components/Home/ListContainer";
import Banner from "@/components/Home/Banner";
import { Suspense } from "react";
import { IList } from "@/interface/listType";
import Layout from "@/components/Layout";


const BaseURL = process.env.NEXTAUTH_URL

export const getStaticProps = async () => {
  const response = await fetch(`${BaseURL}/api/test/list`);
  if(response.ok){
    const data = await response.json();
    return { props: { data }}
  }else{
    throw new Error('API 에러')
  }
}

export default function Home({ data }: { data: IList[]}) {
  console.log(data)
  return (
    <>
      <Head>
        <title>퀄슨 테스트 목록</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header text="테스트 목록"/>
        <Banner/>
        <Suspense fallback={<div>Loading...</div>}>
          <ListContainer data={data}/>
        </Suspense>
      </Layout>
    </>
  );
}
